#ifndef JAVASCRIPT_EDITOR_MACROS_H
#define JAVASCRIPT_EDITOR_MACROS_H

#ifndef TOOLS_ENABLED
#error CAN NOT COMPILE WITHOUT TOOLS_ENABLED, PLEASE CHECK IT'S NOT UNEXPECTEDLY INCLUDED.
#endif

#include "../internal/jsb_macros.h"

#endif
