
DEF(Vector2)
DEF(Vector2i)
DEF(Rect2)
DEF(Rect2i)
DEF(Vector3)
DEF(Vector3i)
DEF(Transform2D)
DEF(Vector4)
DEF(Vector4i)
DEF(Plane)
DEF(Quaternion)
DEF(AABB)
DEF(Basis)
DEF(Transform3D)
DEF(Projection)
DEF(Color)
// - StringName
DEF(NodePath)
DEF(RID)
// - Object
DEF(Callable)
DEF(Signal)
DEF(Dictionary)
DEF(Array)
DEF(PackedByteArray)
DEF(PackedInt32Array)
DEF(PackedInt64Array)
DEF(PackedFloat32Array)
DEF(PackedFloat64Array)
DEF(PackedStringArray)
DEF(PackedVector2Array)
DEF(PackedVector3Array)
#if GODOT_4_3_OR_NEWER
DEF(PackedVector4Array)
#endif
DEF(PackedColorArray)
