#ifndef DEF
#error "DO NOT INCLUDE THIS FILE AS A HEADER"
#else
DEF(NIL)

// atomic types
DEF(BOOL)
DEF(INT)
DEF(FLOAT)
DEF(STRING)

// math types
DEF(VECTOR2)
DEF(VECTOR2I)
DEF(RECT2)
DEF(RECT2I)
DEF(VECTOR3)
DEF(VECTOR3I)
DEF(TRANSFORM2D)
DEF(VECTOR4)
DEF(VECTOR4I)
DEF(PLANE)
DEF(QUATERNION)
DEF(AABB)
DEF(BASIS)
DEF(TRANSFORM3D)
DEF(PROJECTION)

// misc types
DEF(COLOR)
DEF(STRING_NAME)
DEF(NODE_PATH)
DEF(RID)
DEF(OBJECT)
DEF(CALLABLE)
DEF(SIGNAL)
DEF(DICTIONARY)
DEF(ARRAY)

// typed arrays
DEF(PACKED_BYTE_ARRAY)
DEF(PACKED_INT32_ARRAY)
DEF(PACKED_INT64_ARRAY)
DEF(PACKED_FLOAT32_ARRAY)
DEF(PACKED_FLOAT64_ARRAY)
DEF(PACKED_STRING_ARRAY)
DEF(PACKED_VECTOR2_ARRAY)
DEF(PACKED_VECTOR3_ARRAY)
DEF(PACKED_COLOR_ARRAY)

DEF(VARIANT_MAX)
#endif
