name: 🌳 Set Environment
on:
  workflow_call:

jobs:
  environment:
    name: 🌳 Set Environment
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v6

      - name: 🛠️ pnpm and build
        uses: ./.github/actions/pnpm-build

      - name: ⬆️ Upload scripts/out
        uses: actions/upload-artifact@v4
        with:
          name: scripts-out
          path: ${{github.workspace}}/scripts/out
          retention-days: 10

      - name: ⬆️ Upload tests/project
        uses: actions/upload-artifact@v4
        with:
          name: tests-project
          path: ${{github.workspace}}/tests/project/.godot/GodotJS
          retention-days: 10

      - name: ⬆️ Upload impl/web/js
        uses: actions/upload-artifact@v4
        with:
          name: impl-web-js
          path: ${{github.workspace}}/impl/web/js
          retention-days: 10
