name: 🔗 GHA

# Only run pipeline on open pull_requests and main + releases
# we don't need it on every push and some parameters are not available for push only
on:
  pull_request:
  push:
    branches:
      - "main"
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  environment:
    name: 🌳 Set Environment
    uses: ./.github/workflows/misc_environment.yml

  changesets:
    if: github.event_name != 'release' && github.event_name != 'pull_request'
    permissions:
      contents: write
      pull-requests: write
    name: 🔄 Changesets
    uses: ./.github/workflows/misc_changesets.yml

  engine-version-build:
    name: ⚙️ Build Godot Version with GodotJS
    needs: [environment]
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 4.6.1
            version_mm: 4.6
            version_ref: 4.6.1-stable
#          - version: 4.7dev
#            version_mm: 4.7
#            version_ref: master
    uses: ./.github/workflows/build_engine_version.yml
    with:
      version: ${{ matrix.version }}
      version_mm: ${{ matrix.version_mm }}
      version_ref: ${{ matrix.version_ref }}
      release: ${{ github.event_name == 'release' }}

  runtime-matrix:
    name: 🧪 Runtime matrix
    needs: [engine-version-build]
    uses: ./.github/workflows/test_runtime_matrix.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 4.6.1
#          - version: 4.7dev
    with:
      version: ${{ matrix.version }}

  builds-done:
    name: 🏁 Builds Done
    needs: [runtime-matrix]
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Check if all builds are done
        run: |
          echo "🏁 All builds done"
        shell: bash

  release:
    name: 🦅 Release
    needs: [changesets, builds-done]
    if: needs.changesets.outputs.publish == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/misc_release.yml
    secrets: inherit
    with:
      versions: '4.6.1'
#      versions: '4.6.1, 4.7'

  upload-assets:
    name: 📁 Upload Assets
    needs: [builds-done]
    if: github.event_name == 'release'
    permissions:
      contents: write
    uses: ./.github/workflows/misc_upload_assets.yml
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        include:
          - version: 4.6.1
#          - version: 4.7dev
    with:
      version: ${{ matrix.version }}
